package com.github.jdw.seaofshadows.shared.webgl.interfaces

/**
 * The WebGLTransformFeedback interface is part of the WebGL 2 API and enables transform feedback, which is the process of capturing primitives generated by vertex processing. It allows to preserve the post-transform rendering state of an object and resubmit this data multiple times.
 *
 * When working with WebGLTransformFeedback objects, the following methods of the WebGL2RenderingContext are useful:
 * * [WebGL2RenderingContext.createTransformFeedback]
 * * [WebGL2RenderingContext.deleteTransformFeedback]
 * * [WebGL2RenderingContext.isTransformFeedback]
 * * [WebGL2RenderingContext.bindTransformFeedback]
 * * [WebGL2RenderingContext.beginTransformFeedback]
 * * [WebGL2RenderingContext.endTransformFeedback]
 * * [WebGL2RenderingContext.pauseTransformFeedback]
 * * [WebGL2RenderingContext.resumeTransformFeedback]
 * * [WebGL2RenderingContext.transformFeedbackVaryings]
 * * [WebGL2RenderingContext.getTransformFeedbackVarying]
 *
 * See more: https://developer.mozilla.org/en-US/docs/Web/API/WebGLTransformFeedback
 */
interface WebGLTransformFeedback: WebGLObject